name: CLUSTERJHEP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - scipy=1.11.1
  - seaborn=0.12.2
  - numpy=1.24.3
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
    - lifelines==0.28.0
    - statsmodels==0.14.0
